if (Meteor.isClient) {

  Template.hello.helpers({
    loc: function() {
      return getLocation();
    },
    uid: function() {
      return Meteor.userId();
    }
  });

  Meteor.startup(function () {
    initLocation();
    Session.set('currentuser', 'something randomly generated by another function');
  });

}

if (Meteor.isServer) {
  Meteor.startup(function() {
    // code to run on server at startup
  });
}
